#include "TTree.h"
#include "TChain.h"
#include "TBranch.h"


const UInt_t maxmc  = 50;
const UInt_t maxln  = 50;
const UInt_t maxjn  = 50;
const UInt_t maxmet = 50;

// Tree variables
Int_t cat;
Int_t mccat;
Int_t ngenITpu;
Int_t nvtx;
Float_t l1_px;
Float_t l1_py;
Float_t l1_pz;
Float_t l1_en;
Float_t l1_ptErr;
Int_t   l1_id;
Float_t l2_px;
Float_t l2_py;
Float_t l2_pz;
Float_t l2_en;
Float_t l2_ptErr;
Int_t   l2_id;
Int_t   ln;
Float_t ln_px[maxln];
Float_t ln_py[maxln];
Float_t ln_pz[maxln];
Float_t ln_en[maxln];
Float_t ln_ptErr[maxln];
Int_t   ln_id[maxln];
Int_t   jnum;
Float_t jn_px[maxjn];
Float_t jn_py[maxjn];
Float_t jn_pz[maxjn];
Float_t jn_en[maxjn];
Float_t jn_btag1[maxjn];
Float_t jn_btag2[maxjn];
Bool_t  jn_tightId[maxjn];
Float_t htvec_px;
Float_t htvec_py;
Float_t met_pt[maxmet];
Float_t met_phi[maxmet];
Float_t mc_px[maxmc];
Float_t mc_py[maxmc];
Float_t mc_pz[maxmc];
Float_t mc_en[maxmc];
Int_t   mc_id[maxmc];

Float_t dilepPROJLong;
Float_t dilepPROJPerp;
Float_t sumjetPROJLong;
Float_t sumjetPROJPerp;
Float_t unclPROJLong;
Float_t unclPROJPerp;
Float_t recoilPROJLong;
Float_t recoilPROJPerp;
Float_t uncertPROJLong;
Float_t uncertPROJPerp;
Float_t cosphi;
Float_t Mass_Z;
Float_t Pt_Z;
Float_t DeltaPhi_ll;
int Cosmic;
Float_t Pt_J1;
Float_t pfMEToverPt_Z;
Float_t DeltaPhi_metjet;
Float_t RMET_cosangle;
Float_t Pt_L1;
Float_t Pt_L2;
Float_t P_L1;
Float_t P_L2;
Float_t DeltaPhi_ZH;
Float_t DeltaPhi_L1H;
Float_t DeltaPhi_ZH_uncl;
Float_t DeltaPhi_L1H_uncl;
Float_t DeltaPhi_L2H_uncl;
Float_t DeltaPhi_L1Z;
Float_t DeltaPhi_L2Z;
Float_t TransMass_Z;
Float_t TransMass_ZH0;
Float_t TransMass_ZH150;
Float_t TransMass_ZH105;
Float_t TransMass_ZH115;
Float_t TransMass_ZH125;
Float_t TransMass_ZH0_uncl;
Float_t TransMass_ZH150_uncl;
Float_t TransMass_ZH105_uncl;
Float_t TransMass_ZH115_uncl;
Float_t TransMass_ZH125_uncl;
Float_t L1Z_cosangle;
Float_t CS_cosangle;
Float_t CMAngle;
Float_t Z_eta;
Float_t Z_rapidity;
Float_t L1_L2_cosangle;
Float_t NumGenEvents;
Float_t CrossSection;
Float_t PU_ratio;
Float_t evtWeight;
Float_t btag_CSV_max;
Float_t Z_rapidity_z;
Float_t THRUST_2D;
Float_t THRUST_3D;
Float_t redMETd0_muon_DYZZ;
Float_t redMETd0_elec_DYZZ;
Float_t redMETd0_combo_DYZZ;
Float_t redMETCMS_muon_DYZZ;
Float_t redMETCMS_elec_DYZZ;
Float_t redMETCMS_combo_DYZZ;
int jet_index_btag_CSV_max;
Float_t Pt_Jet_btag_CSV_max;


// Initialize variables
void initializeTreeVariables() {

  cat = 0;
  mccat = 0;
  ngenITpu = 0;
  nvtx = 0;
  l1_px = 0.;
  l1_py = 0.;
  l1_pz = 0.;
  l1_en = 0.;
  l1_ptErr = 0.;
  l1_id = 0;
  l2_px = 0.;
  l2_py = 0.;
  l2_pz = 0.;
  l2_en = 0.;
  l2_ptErr = 0.;
  l2_id = 0;
  ln = 0;
  for(unsigned int i=0; i<maxln; ++i) {
    ln_px[i] = 0.;
    ln_py[i] = 0.;
    ln_pz[i] = 0.;
    ln_en[i] = 0.;
    ln_ptErr[i] = 0.;
    ln_id[i] = 0;
  }
  jnum = 0;
  for(unsigned int i=0; i<maxln; ++i) {
    jn_px[i] = 0.;
    jn_py[i] = 0.;
    jn_pz[i] = 0.;
    jn_en[i] = 0.;
    jn_btag1[i] = 0.;
    jn_btag2[i] = 0.;
    jn_tightId[i] = false;
  }
  htvec_px = 0.;
  htvec_py = 0.;
  for(unsigned int i=0; i<maxmet; ++i) {
    met_pt[i] = 0.;
    met_phi[i] = 0.;
  }
  for(unsigned int i=0; i<maxmc; ++i) {
    mc_px[i] = 0.;
    mc_py[i] = 0.;
    mc_pz[i] = 0.;
    mc_en[i] = 0.;
    mc_id[i] = 0;
  }
  
 dilepPROJLong=0;
 dilepPROJPerp=0;
 sumjetPROJLong=0;
 sumjetPROJPerp=0;
 unclPROJLong=0;
 unclPROJPerp=0;
 recoilPROJLong=0;
 recoilPROJPerp=0;
 uncertPROJLong=0;
 uncertPROJPerp=0;
 cosphi=0;
 Mass_Z=0;
 Pt_Z=0;
 DeltaPhi_ll=0;
 Cosmic=0;
 Pt_J1=0;
 pfMEToverPt_Z=0;
 DeltaPhi_metjet=0;
 RMET_cosangle=0;
 Pt_L1=0;
 Pt_L2=0;
 P_L1=0;
 P_L2=0;
 DeltaPhi_ZH=0;
 DeltaPhi_L1H=0;
 DeltaPhi_ZH_uncl=0;
 DeltaPhi_L1H_uncl=0;
 DeltaPhi_L2H_uncl=0;
 DeltaPhi_L1Z=0;
 DeltaPhi_L2Z=0;
 TransMass_Z=0;
 TransMass_ZH0=0;
 TransMass_ZH150=0;
 TransMass_ZH105=0;
 TransMass_ZH115=0;
 TransMass_ZH125=0;
 TransMass_ZH0_uncl=0;
 TransMass_ZH150_uncl=0;
 TransMass_ZH105_uncl=0;
 TransMass_ZH115_uncl=0;
 TransMass_ZH125_uncl=0;
 L1Z_cosangle=0;
 CS_cosangle=0;
 CMAngle=0;
 Z_eta=0;
 Z_rapidity=0;
 L1_L2_cosangle=0;
 NumGenEvents=0;
 CrossSection=0;
 PU_ratio=0;
 evtWeight=0;
 btag_CSV_max=0;
 Z_rapidity_z=0;
 THRUST_2D=0;
 THRUST_3D=0;
 redMETd0_muon_DYZZ=0;
 redMETd0_elec_DYZZ=0;
 redMETd0_combo_DYZZ=0;
 redMETCMS_muon_DYZZ=0;
 redMETCMS_elec_DYZZ=0;
 redMETCMS_combo_DYZZ=0;
 jet_index_btag_CSV_max=0;
 Pt_Jet_btag_CSV_max=0;
  
}

// Set branch addresses
void attachToTree(TChain *t) {

  t->SetBranchAddress("cat", &cat);
  t->SetBranchAddress("mccat", &mccat);
  t->SetBranchAddress("ngenITpu", &ngenITpu);
  t->SetBranchAddress("nvtx", &nvtx);
  t->SetBranchAddress("l1_px", &l1_px);
  t->SetBranchAddress("l1_py", &l1_py);
  t->SetBranchAddress("l1_pz", &l1_pz);
  t->SetBranchAddress("l1_en", &l1_en);
  t->SetBranchAddress("l1_ptErr", &l1_ptErr);
  t->SetBranchAddress("l1_id", &l1_id);
  t->SetBranchAddress("l2_px", &l2_px);
  t->SetBranchAddress("l2_py", &l2_py);
  t->SetBranchAddress("l2_pz", &l2_pz);
  t->SetBranchAddress("l2_en", &l2_en);
  t->SetBranchAddress("l2_ptErr", &l2_ptErr);
  t->SetBranchAddress("l2_id", &l2_id);
  t->SetBranchAddress("ln", &ln);
  t->SetBranchAddress("ln_px", &ln_px);
  t->SetBranchAddress("ln_py", &ln_py);
  t->SetBranchAddress("ln_pz", &ln_pz);
  t->SetBranchAddress("ln_en", &ln_en);
  t->SetBranchAddress("ln_ptErr", &ln_ptErr);
  t->SetBranchAddress("ln_id", &ln_id);
  t->SetBranchAddress("jn", &jnum);
  t->SetBranchAddress("jn_px", &jn_px);
  t->SetBranchAddress("jn_py", &jn_py);
  t->SetBranchAddress("jn_pz", &jn_pz);
  t->SetBranchAddress("jn_en", &jn_en);
  t->SetBranchAddress("jn_btag1", &jn_btag1);
  t->SetBranchAddress("jn_btag2", &jn_btag2);
  //t->SetBranchAddress("jn_tightId", &jn_tightId);
  //t->SetBranchAddress("htvec_px", &htvec_px);
  //t->SetBranchAddress("htvec_py", &htvec_py);
  t->SetBranchAddress("met_pt", &met_pt);
  t->SetBranchAddress("met_phi", &met_phi);
  t->SetBranchAddress("mc_px", &mc_px);
  t->SetBranchAddress("mc_py", &mc_py);
  t->SetBranchAddress("mc_pz", &mc_pz);
  t->SetBranchAddress("mc_en", &mc_en);
  t->SetBranchAddress("mc_id", &mc_id);
  
 t->SetBranchAddress("dilepPROJLong", &dilepPROJLong);         
 t->SetBranchAddress("dilepPROJPerp", &dilepPROJPerp);
 t->SetBranchAddress("sumjetPROJLong", &sumjetPROJLong);
 t->SetBranchAddress("sumjetPROJPerp", &sumjetPROJPerp);
 t->SetBranchAddress("unclPROJLong", &unclPROJLong);
 t->SetBranchAddress("unclPROJPerp", &unclPROJPerp);
 t->SetBranchAddress("recoilPROJLong", &recoilPROJLong);
 t->SetBranchAddress("recoilPROJPerp", &recoilPROJPerp);
 t->SetBranchAddress("uncertPROJLong", &uncertPROJLong);
 t->SetBranchAddress("uncertPROJPerp", &uncertPROJPerp);
 t->SetBranchAddress("cosphi", &cosphi);
 t->SetBranchAddress("Mass_Z", &Mass_Z);
 t->SetBranchAddress("Pt_Z", &Pt_Z);
 t->SetBranchAddress("DeltaPhi_ll", &DeltaPhi_ll);
 t->SetBranchAddress("Cosmic", &Cosmic);
 t->SetBranchAddress("Pt_J1", &Pt_J1);
 t->SetBranchAddress("pfMEToverPt_Z", &pfMEToverPt_Z);
 t->SetBranchAddress("DeltaPhi_metjet", &DeltaPhi_metjet);
 t->SetBranchAddress("RMET_cosangle", &RMET_cosangle);
 t->SetBranchAddress("Pt_L1", &Pt_L1);
 t->SetBranchAddress("Pt_L2", &Pt_L2);
 t->SetBranchAddress("P_L1", &P_L1);
 t->SetBranchAddress("P_L2", &P_L2);
 t->SetBranchAddress("DeltaPhi_ZH", &DeltaPhi_ZH);
 t->SetBranchAddress("DeltaPhi_L1H", &DeltaPhi_L1H);
 t->SetBranchAddress("DeltaPhi_ZH_uncl", &DeltaPhi_ZH_uncl);
 t->SetBranchAddress("DeltaPhi_L1H_uncl", &DeltaPhi_L1H_uncl);
 t->SetBranchAddress("DeltaPhi_L2H_uncl", &DeltaPhi_L2H_uncl);
 t->SetBranchAddress("DeltaPhi_L1Z", &DeltaPhi_L1Z);
 t->SetBranchAddress("DeltaPhi_L2Z", &DeltaPhi_L2Z);
 t->SetBranchAddress("TransMass_Z", &TransMass_Z);
 t->SetBranchAddress("TransMass_ZH0", &TransMass_ZH0);
 t->SetBranchAddress("TransMass_ZH150", &TransMass_ZH150);
 t->SetBranchAddress("TransMass_ZH105", &TransMass_ZH105);
 t->SetBranchAddress("TransMass_ZH115", &TransMass_ZH115);
 t->SetBranchAddress("TransMass_ZH125", &TransMass_ZH125);
 t->SetBranchAddress("TransMass_ZH0_uncl", &TransMass_ZH0_uncl);
 t->SetBranchAddress("TransMass_ZH150_uncl", &TransMass_ZH150_uncl);
 t->SetBranchAddress("TransMass_ZH105_uncl", &TransMass_ZH105_uncl);
 t->SetBranchAddress("TransMass_ZH115_uncl", &TransMass_ZH115_uncl);
 t->SetBranchAddress("TransMass_ZH125_uncl", &TransMass_ZH125_uncl);
 t->SetBranchAddress("L1Z_cosangle", &L1Z_cosangle);
 t->SetBranchAddress("CS_cosangle", &CS_cosangle);
 t->SetBranchAddress("CMAngle", &CMAngle);
 t->SetBranchAddress("Z_eta", &Z_eta);
 t->SetBranchAddress("Z_rapidity", &Z_rapidity);
 t->SetBranchAddress("L1_L2_cosangle", &L1_L2_cosangle);
 t->SetBranchAddress("NumGenEvents", &NumGenEvents);
 t->SetBranchAddress("CrossSection", &CrossSection);
 t->SetBranchAddress("PU_ratio", &PU_ratio);
 t->SetBranchAddress("evtWeight", &evtWeight);
 t->SetBranchAddress("btag_CSV_max", &btag_CSV_max);
 t->SetBranchAddress("Z_rapidity_z", &Z_rapidity_z);
 t->SetBranchAddress("THRUST_2D", &THRUST_2D);
 t->SetBranchAddress("THRUST_3D", &THRUST_3D);
 t->SetBranchAddress("redMETd0_muon_DYZZ", &redMETd0_muon_DYZZ);
 t->SetBranchAddress("redMETd0_elec_DYZZ", &redMETd0_elec_DYZZ);
 t->SetBranchAddress("redMETd0_combo_DYZZ", &redMETd0_combo_DYZZ);
 t->SetBranchAddress("redMETCMS_muon_DYZZ", &redMETCMS_muon_DYZZ);
 t->SetBranchAddress("redMETCMS_elec_DYZZ", &redMETCMS_elec_DYZZ);
 t->SetBranchAddress("redMETCMS_combo_DYZZ", &redMETCMS_combo_DYZZ);
 t->SetBranchAddress("jet_index_btag_CSV_max", &jet_index_btag_CSV_max);
 t->SetBranchAddress("Pt_Jet_btag_CSV_max", &Pt_Jet_btag_CSV_max);


}
