#! /usr/bin/env python

import os
import sys
import fileinput
import string
import ROOT
from ROOT import TFile

#unzip output
currentDir = os.popen("ls").readlines()
#for line in currentDir:
#    line = line.rstrip("\n")
#    test = line.find("crab_0",0,20)
#    if test == 0:
#        crabDir=line
#outputDir = os.popen("ls "+crabDir+"/res/*.tgz").readlines()
#for line in outputDir:
#    line = line.rstrip("\n")
#    os.system("tar -xzvf "+line)

print "unzipped output"

#hadd the root files
os.system("hadd OUTPUTFILE valHists_run*")
#os.system("hadd TPEHists.root TPEHists*.root")

print "hadded output"

#make the plots
os.system("root -l -q -b makePlots.C")
#os.system("root -l -q -b TPEHists.root ../../templates/makePlots_emulator2.C")
#os.system("root -l -q -b TPEHists.root ../../templates/plot_new.C >bad_TPE_chambers.txt") 
#os.system("root -l -q -b TPEHists.root ../../templates/plot_badwires.C+ >hot_wires.txt")

print "made plots"

#make the web page
os.system("mkdir /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER")
os.system("mkdir /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM")
#os.system("mkdir /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site")
#os.system("mkdir /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site/PNGS")
os.system("cp -r ../../web/* /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM")
os.system("mv Summary.html /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site")
os.system("mv hot_wires.txt /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site/PNGS")
os.system("mv bad_TPE_chambers.txt /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site/PNGS")
os.system("mv TPEHists.root /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site/PNGS")
os.system("mv deadchamberlist.txt /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site/PNGS")
os.system("mv CFGFILE /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site/PNGS/config.py")
os.system("cp *.png /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/results/runRUNNUMBER/STREAM/Site/PNGS")
#os.system("mv OUTPUTFILE /afs/cern.ch/cms/CAF/CMSCOMM/COMM_CSC/CSCVAL/AUTOVAL/rootfiles/")

print "make webpage"
